### ISSUE TITLE
Sette nytt styre

### ISSUE THREAD

**Issue by weblady** [webrtd/website#122]
Det kommer fortsatt IRO og GL når styret settes. Håper dette kan fikses. Klubbene får ikke satt styrer uten å ta med IRO og GL nå. Det blir mye vi må rette opp i manuelt. Mange mailer fra klubber ang dette og at det må godkjennes av LF ang medlemmer som ikke har vært med i ett år som skal inn i styret, den beskjeden vil vi ha bort. I tillegg så er alle slike meldinger med RT roller. Også når landssekretær melder ut medlemmer. Dette er sendt mail om tidligere, men muligens ikke lagt inn i github. Har du mulighet til å gi tilbakemelding om når dette kan fikses?

**Comment by webrtd** [comment]
Hej

Systemet siger at alle de roller der indgår i en bestyrelser skal besættes
ved generalforsamlingen. Skal det forståes som at GL/IRO skal fjernes fra
listen over roller?

LF godkendelser kommer, så vidt jeg husker, blot som en "besked /
notifikation". Det blokerer ikke systemet for at sekretæren kan indstille
bestyrelsen.

Ny bestyrelse i LCN-systemet har pt følgende regler:

- Alle poster av styret skal være ferdig for nominasjoner kan foretas
- Minst ett medlem av det nåværende styret skal gjenvelges til det nye
styret
- Maks tre medlemmer av det nåværende styret kan gjenvelges.
- Det valgte medlemmet har trukket set fra Ladies Circle Norge ved
tiltredelsespunktet
- Det valgte medlemmet er uenig i valgt post i nåværende periode.
- Medlemmet skal ha vært medlem av Ladies Circle Norge i minst ett år ved
tiltredelsespunktet

De kommer alle som en notifikation, men blokerer IKKE systemet.

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-05-18 12:01 GMT+05:30 weblady <notifications@github.com>:

**Comment by weblady** [comment]
Vi har ikke de samme reglene i LCN som RT, så de reglene som du nevnte der gjelder ikke for oss. 

Vi ønsker IRO slettet som rolle ja, den ligger det et par tickets om her i github fra tidligere. Står hvertfall på #114. GL er vel styremedlem (?), vi vil ha med det som en rolle fortsatt, men det er ikke noe krav i LC å ha styremedlem med i klubbstyret, det er valgfritt. 

Det med LF godkjennelse er ingen regel i LC og ikke en del av vår matrikkel, og derfor ønsker vi det fjernet siden det bare fører til forvirring hos medlemmene og vi får masse spørsmål rundt det.

**Comment by weblady** [comment]
Fant ut at GL er gruppe leder og skal dermed fjernes, det står nok også på #114. Styremedlem ligger inne som rolle, den vil vi fremdeles ha som rolle, men ikke som krav for å sette nytt styre.

**Comment by webrtd** [comment]
Jeg har ændret så LF godkendelse ikke kommer frem og IRO ikke længere er
behøvet. Vil du se om det har løst problemet?

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-05-18 17:07 GMT+05:30 weblady <notifications@github.com>:

**Comment by weblady** [comment]
Jeg skal teste så snart jeg har noe å teste med. Tusen takk for kjapp behandling i dag!

**Comment by weblady** [comment]
Hei

Nå fikk jeg testet det, da klubben min hadde generalforsamling i kveld :) Det fungerer nesten som det skal nå, men jeg får fremdeles beskjed om at styremedlem må settes for å få lov til å sette nytt styre, og hos oss er det ikke påkrevd å ha med styremedlem i klubbstyrer. Gjerne fjern denne også :)

 

 

Silje

**Comment by weblady** [comment]
Hei

 

Vil du fjerne styremedlem som krav for å sette nytt styre i LC så fort som mulig? Vi får mye mas om dette fra klubbene i disse dager som alle skal sette nye styrer. 

 

 

Silje

**Comment by weblady** [comment]
Prøv at se om det virker nu

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-05-28 14:04 GMT+02:00 Weblady LC Norge <web@lcnorge.no>:
