### ISSUE TITLE
Legge inn tidligere møter

### ISSUE THREAD

**Issue by weblady** [webrtd/website#127]
Nå får vi ikke lagt inn møter tilbake i tid. De blir registrert og vises når jeg har lagret dem, men når jeg så går inn på klubbsiden og ser på arkiv over gamle møter så ligger de ikke der. Dette har jeg gjort tidligere så det skal gå an.

**Comment by webrtd** [comment]
Prøv at sende et link til eksempel. Der er ikke rettet i den funktionalitet.

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-08-11 8:59 GMT+02:00 weblady <notifications@github.com>:

**Comment by weblady** [comment]
Jeg testet dette igjen nå uten å få feil. Lukker saken
