### ISSUE TITLE
RTN: LSK får ikke lenger lov til å sende nyhetsbrev

### ISSUE THREAD

**Issue by webmasterRTN** [webrtd/website#134]
RTN LSK får ikke lenger lov til å markere mottakere av nyhetsbrev, Han får heller ikke lov til å endre UID på utsending. Dette har fungert tidligere.

**Comment by webrtd** [comment]
Prøv nu

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-09-06 20:35 GMT+02:00 webmasterRTN <notifications@github.com>:

**Comment by webmasterRTN** [comment]
Fortsatt problem dessverre..

**Comment by webrtd** [comment]
Send login info på mail til web@rtd.dk så kigger jeg på det

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-09-07 10:09 GMT+02:00 webmasterRTN <notifications@github.com>:

**Comment by webmasterRTN** [comment]
Problem løst! :)
