### ISSUE TITLE
RTN: Avgåtte medlemmer blir automatisk påmeldt klubbmøter

### ISSUE THREAD

**Issue by webmasterRTN** [webrtd/website#135]
Vi har et problem med at 2 avgåtte medlemmer blir påmeldt alle klubbmøtene.

Gjelder uid=1324 og uid=5452

Kan dette ses på snarest (det har vært en misforståelse som har gjort at klubben har ventet en stund på å få dette fikset)?

**Comment by webrtd** [comment]
Tjek at udmeldelsesdato på profil og rolle matcher. Husk at udmelde via Udmeld-funktion på profilen. 

Mvh
Rasmus Kaae, +45-28720413
www.coursetool.org

**Comment by webmasterRTN** [comment]
Fikset det ved å slette rolle og legge denne inn igjen og samtidig redigere og lagre profilen igjen.

 

 

Mvh

Alexander

**Comment by webrtd** [comment]
Super :)

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-11-02 15:46 GMT+01:00 webmasterRTN <notifications@github.com>:
