### ISSUE TITLE
Fødselsdato på nye medlemmer

### ISSUE THREAD

**Issue by weblady** [webrtd/website#81]
Når man skal legge til et nytt medlem i en klubb og skal velge fødselsdato i kalenderen, så får man ikke  valgt dato tidligere enn 2005. En liten bug der altså, men man kan gå rundt det ved å bare velge en dato, og deretter overstyre tallene ved å skrive inn datoen manuelt.

**Comment by webrtd** [comment]
Ja, det er en "begrænsning" i den komponent der bliver brugt. Man kan også
vælge 2005. Vente lidt og så gå 10 år mere tilbage osv.

----------------------------------------------------
Med venlig hilsen / Best regards
Rasmus Kaae, Formand 2014-2015, RT111 Favrskov <http://www.rt111.dk>
National Webmaster since 2011, Round Table Denmark <http://www.rtd.dk>

----------------------------------------------------

2015-01-16 12:18 GMT+01:00 weblady <notifications@github.com>:

**Comment by weblady** [comment]
Takk, ja nå ser jeg at det fungerer som du sier. Vi bare presiserer dette i bruksanvisningen vår :)

 

God helg!

 

 

Silje
